# Generated by Django 2.0.6 on 2018-06-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20180614_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload/category/%Y/%m/%d'),
        ),
    ]
