# Generated by Django 2.0.6 on 2018-06-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='upload/cycle/variation/%Y/%m/%d')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimages', to='supplier.Cycle')),
            ],
        ),
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('color', 'color')], default='color', max_length=120),
        ),
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.ProductImage'),
        ),
    ]
